FROM {{distro.dh}}:{{distro.ver}}
LABEL maintainer "os@safl.dk"
RUN mkdir -p /root/xnvme
WORKDIR /root/xnvme
COPY xnvme .
RUN bash -e ./toolbox/pkgs/{{distro.os}}-{{distro.ver}}.sh
WORKDIR /root
CMD ["bash"]
