FROM {{distro.dh}}:{{distro.ver}}
LABEL maintainer "os@safl.dk"
RUN mkdir -p /root/xnvme
WORKDIR /root/xnvme
COPY xnvme .
RUN bash ./toolbox/pkgs/{{distro.os}}-{{distro.ver}}.sh
WORKDIR /root
RUN rm -rf /root/xnvme
