---
name: dcgen

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  schedule:
    - cron: '0 */12 * * *'

defaults:
  run:
    shell: bash

jobs:
  dockerize:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container:
        - {os: 'alpine', dh: 'refenv/alpine-bash', ver: 'latest'}
        - {os: 'archlinux', dh: 'archlinux', ver: 'latest'}
        - {os: 'centos', dh: 'tgagor/centos', ver: 'stream9'}
        - {os: 'centos', dh: 'tgagor/centos', ver: 'stream8'}
        - {os: 'centos', dh: 'centos', ver: 'centos7'}
        - {os: 'citools', dh: '', ver: 'latest'}
        - {os: 'debian', dh: 'debian', ver: 'bookworm'}
        - {os: 'debian', dh: 'debian', ver: 'bullseye'}
        - {os: 'debian', dh: 'debian', ver: 'buster'}
        - {os: 'fedora', dh: 'fedora', ver: '36'}
        - {os: 'fedora', dh: 'fedora', ver: '35'}
        - {os: 'fedora', dh: 'fedora', ver: '34'}
        - {os: 'gentoo', dh: 'gentoo/stage3', ver: 'latest'}
        - {os: 'opensuse-tumbleweed', dh: 'opensuse/tumbleweed', ver: 'latest'}
        - {os: 'opensuse-leap', dh: 'opensuse/leap', ver: '15.4'}
        - {os: 'opensuse-leap', dh: 'opensuse/leap', ver: '15.3'}
        - {os: 'ubuntu', dh: 'ubuntu', ver: 'jammy'}
        - {os: 'ubuntu', dh: 'ubuntu', ver: 'focal'}
        - {os: 'ubuntu', dh: 'ubuntu', ver: 'bionic'}

    env:
      XNVME_REF: next

    steps:
    - name: Grab xnvme-docker
      uses: actions/checkout@v3.1.0

    - name: Grab xNVMe
      run: |
        mkdir -p builddir/xnvme
        curl -L https://github.com/OpenMPDK/xNVMe/tarball/${XNVME_REF} -o xnvme.tgz
        tar xzf xnvme.tgz --strip-components=1 -C builddir/xnvme

    - name: Build
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/xnvme-deps-${{ matrix.container.os }}-${{ matrix.container.ver }}:${XNVME_REF}
        docker build \
        -t $IMAGE_ID \
        -t xnvme-deps-${{ matrix.container.os }}-${{ matrix.container.ver }}:${XNVME_REF} \
        -f dockerfiles/${{ matrix.container.os }}/${{ matrix.container.ver }}/Dockerfile \
        builddir

    - name: Log into GitHub Container Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push to ghcr.io
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/xnvme-deps-${{ matrix.container.os }}-${{ matrix.container.ver }}:${XNVME_REF}
        docker push $IMAGE_ID
